kind: PersistentVolume
apiVersion: v1
metadata:
  name: platforms-pgsql-pv
  labels:
    type: local
    app: platforms-pgsql
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: platforms-pgsql-pvc
  labels:
    app: platforms-pgsql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi